spring:
  profiles: local-dev
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/carts
    username: root
    password: akash

  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  hibernate:
    ddl-auto: create

  kafka:
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: '*'

server:
  port: 8084
