spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:8082
      group-id: user_service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:8082
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  profiles: local-dev
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: akash

  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  hibernate:
    ddl-auto: create

server:
  port: 8082
