spring:
  cloud:
    gateway:
      routes:
        - id: sessionMicroService
          uri: "http://localhost:8081"
          predicates:
            - Path=/api/v1/sessions/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

        - id: userMicroService
          uri: "http://localhost:8082"
          predicates:
            - Path=/api/v1/users/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

        - id: productMicroService
          uri: "http://localhost:8083"
          predicates:
            - Path=/api/v1/products/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

        - id: cartMicroService
          uri: "http://localhost:8084"
          predicates:
            - Path=/api/v1/carts/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

        - id: wishlistMicroService
          uri: "http://localhost:8085"
          predicates:
            - Path=/api/v1/wishlists/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

        - id: ordersMicroService
          uri: "http://localhost:8086"
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

        - id: reviewsMicroService
          uri: "http://localhost:8087"
          predicates:
            - Path=/api/v1/reviews/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
  profiles:
    include:
      - api

server:
  port: 8090