spring:
  profiles: local-dev
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/orders
    username: root
    password: akash

  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  hibernate:
    ddl-auto: create

  artemis:
    user: artemis
    password: simetraechcapa

server:
  port: 8086
