package com.ecom.user.states.user;

public enum UserCreationEvent {
    CREATE_USER_SERVICE,
    USER_SERVICE_FAILED,
    CREATE_SESSION_SERVICE,
    SESSION_SERVICE_FAILED,
    CREATE_CART_SERVICE,
    CART_SERVICE_FAILED,
    CREATE_WISHLIST_SERVICE,
    WISHLIST_SERVICE_FAILED,
    CREATE_ORDERS_SERVICE,
    ORDER_SERVICE_FAILED,
    COMPLETED
}
